import treesitter from 'eslint-config-treesitter';

/**
 * Lints grammar.js (the reason this exists) and the node bindings.
 *
 * `web/` is a separate Vite app with its own toolchain and its own eslint
 * dependency; it is ignored here so the two never fight over the same files.
 */
export default [
  {
    ignores: [
      'src/**', // generated parser artifacts
      'bindings/**', // tree-sitter CLI boilerplate, regenerated by `tree-sitter init`
      'web/**', // separate app, own config
      'node_modules/**',
      'target/**',
    ],
  },
  ...treesitter,
  {
    files: ['grammar.js'],
    rules: {
      // The PREC table and rule bodies are aligned in columns for readability;
      // eslint's `no-multi-spaces` would flatten that.
      'no-multi-spaces': 'off',
      // `//#region` / `//#endregion` fold markers organize grammar.js and must
      // keep their leading `#` unspaced. `///` is the DSL type reference.
      'spaced-comment': ['error', 'always', {line: {markers: ['/', '#']}}],
    },
  },
];
